import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {NewsProvider} from "@/context/NewsContext";
import Header from "@/components/Header";
import Banner from "@/components/Banner";
import { Toaster } from 'react-hot-toast';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Estadão | As Últimas Notícias do Brasil e do Mundo",
  description: "Generated by create next app",
};

export default function RootLayout({
 children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <NewsProvider>
        <Header />
        <main className="pt-[60px]">
          <Banner />
          <Toaster position="top-right" reverseOrder={false} />
          {children}
        </main>
      </NewsProvider>
      </body>
      </html>
  );
}
