services:
  postgres:
    image: postgres:16
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: estadao
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: server
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/estadao
    depends_on:
      - postgres
    command: sh -c "npx prisma migrate deploy && npm run start:dev"
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: client
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000

volumes:
  postgres_data: