services:
  postgres:
    image: postgres:16
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: estadao
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
